[2025-02-11T12:26:38.639+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_bigquery-test.get_csv_data manual__2025-02-11T12:25:29.370216+00:00 [queued]>
[2025-02-11T12:26:38.663+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_bigquery-test.get_csv_data manual__2025-02-11T12:25:29.370216+00:00 [queued]>
[2025-02-11T12:26:38.665+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2025-02-11T12:26:38.702+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): get_csv_data> on 2025-02-11 12:25:29.370216+00:00
[2025-02-11T12:26:38.713+0000] {standard_task_runner.py:60} INFO - Started process 638 to run task
[2025-02-11T12:26:38.720+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'load_bigquery-test', 'get_csv_data', 'manual__2025-02-11T12:25:29.370216+00:00', '--job-id', '47', '--raw', '--subdir', 'DAGS_FOLDER/load-bigquery-test.py', '--cfg-path', '/tmp/tmpp6qqr30g']
[2025-02-11T12:26:38.725+0000] {standard_task_runner.py:88} INFO - Job 47: Subtask get_csv_data
[2025-02-11T12:26:38.758+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.9/site-packages/airflow/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-02-11T12:26:38.841+0000] {task_command.py:423} INFO - Running <TaskInstance: load_bigquery-test.get_csv_data manual__2025-02-11T12:25:29.370216+00:00 [running]> on host deproject-airflow-scheduler
[2025-02-11T12:26:39.031+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='dibimbing' AIRFLOW_CTX_DAG_ID='load_bigquery-test' AIRFLOW_CTX_TASK_ID='get_csv_data' AIRFLOW_CTX_EXECUTION_DATE='2025-02-11T12:25:29.370216+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-11T12:25:29.370216+00:00'
[2025-02-11T12:26:39.517+0000] {logging_mixin.py:188} INFO -    product_id  customer_id  ...     name.1  price.1
0           1            1  ...  Product A    19.99
1           2            2  ...  Product B     9.99
2           3            3  ...  Product C    15.99
3           4            1  ...  Product D     5.99
4           5            2  ...  Product E    12.99
5           6            3  ...  Product F     9.99
6           7            4  ...  Product G    11.99
7           8            1  ...  Product H    14.99
8           9            2  ...  Product I     9.99
9          10            3  ...  Product J    19.99

[10 rows x 9 columns]
[2025-02-11T12:26:39.519+0000] {logging_mixin.py:188} INFO - Data Load Error: [Errno 2] No such file or directory: '/opt/airflow/cred/operating-ethos-407708-f49bced878c6.json'
[2025-02-11T12:26:39.520+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-02-11T12:26:39.542+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=load_bigquery-test, task_id=get_csv_data, execution_date=20250211T122529, start_date=20250211T122638, end_date=20250211T122639
[2025-02-11T12:26:39.617+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-02-11T12:26:39.673+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
