[2025-02-20T08:32:13.851+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: scraping_news_dag.load_bigquery manual__2025-02-20T08:27:36.086218+00:00 [queued]>
[2025-02-20T08:32:13.862+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: scraping_news_dag.load_bigquery manual__2025-02-20T08:27:36.086218+00:00 [queued]>
[2025-02-20T08:32:13.863+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2025-02-20T08:32:13.878+0000] {taskinstance.py:2214} INFO - Executing <Task(_PythonDecoratedOperator): load_bigquery> on 2025-02-20 08:27:36.086218+00:00
[2025-02-20T08:32:13.883+0000] {standard_task_runner.py:60} INFO - Started process 4817 to run task
[2025-02-20T08:32:13.886+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'scraping_news_dag', 'load_bigquery', 'manual__2025-02-20T08:27:36.086218+00:00', '--job-id', '170', '--raw', '--subdir', 'DAGS_FOLDER/scraping-news-dag.py', '--cfg-path', '/tmp/tmpo6gxs7bq']
[2025-02-20T08:32:13.889+0000] {standard_task_runner.py:88} INFO - Job 170: Subtask load_bigquery
[2025-02-20T08:32:13.904+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.9/site-packages/airflow/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-02-20T08:32:13.944+0000] {task_command.py:423} INFO - Running <TaskInstance: scraping_news_dag.load_bigquery manual__2025-02-20T08:27:36.086218+00:00 [running]> on host deproject-airflow-scheduler
[2025-02-20T08:32:14.056+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='scraping_news_dag' AIRFLOW_CTX_TASK_ID='load_bigquery' AIRFLOW_CTX_EXECUTION_DATE='2025-02-20T08:27:36.086218+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-20T08:27:36.086218+00:00'
[2025-02-20T08:32:14.290+0000] {logging_mixin.py:188} INFO - Data Load Error: [Errno 2] No such file or directory: '/opt/airflow/data/nyt_spark.csv'
[2025-02-20T08:32:14.291+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-02-20T08:32:14.304+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=scraping_news_dag, task_id=load_bigquery, execution_date=20250220T082736, start_date=20250220T083213, end_date=20250220T083214
[2025-02-20T08:32:14.340+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-02-20T08:32:14.372+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
